export const ActionTypes = {
  ASK_PROJECTS_IDS: 'ASK_PROJECTS_IDS',
  INIT_TOKEN_SHARE_STORE: 'INIT_TOKEN_SHARE_STORE',
  GET_REQUIRED_PROJECTS_IDS: 'GET_REQUIRED_PROJECTS_IDS',
  ASK_BACK_URLS: 'ASK_BACK_URLS',
  STORE_BACK_URLS: 'STORE_BACK_URLS',
  SHARE_TOKEN: 'SHARE_TOKEN',
  VALIDATE_SHARED_TOKEN: 'VALIDATE_SHARED_TOKEN',
  SET_PRODUCT_BTN_LOADING: 'SET_PRODUCT_BTN_LOADING',
  SET_PRODUCT_BTN_READY: 'SET_PRODUCT_BTN_READY',
  SET_PRODUCT_BTN_LOCKED: 'SET_PRODUCT_BTN_LOCKED',
  RESET_TOKEN_SHARE: 'RESET_TOKEN_SHARE',
  GET_EXTERNALS_FOR_TOKEN_SHARE: 'GET_EXTERNALS_FOR_TOKEN_SHARE',
  SAVE_CURRENT_URL: 'SAVE_CURRENT_URL',

  //  auth-and-share:
  LISTEN_GRANT_AUTH: 'LISTEN_GRANT_AUTH',
  LISTEN_VALIDATE_SHARE_TOKEN: 'LISTEN_VALIDATE_SHARE_TOKEN',
  SEND_AUTH_DONE_EVENT: 'SEND_AUTH_DONE_EVENT',
  SET_PRODUCT_BTN_COLLAPSED: 'SET_PRODUCT_BTN_COLLAPSED',
  GO_TO_LAST_URL: 'GO_TO_LAST_URL'

} as const;

export type ActionType = keyof typeof ActionTypes;